# -*- coding: utf-8 -*-
# Vertaalkaart, deel 2: koppen, labels, knoppen en alt-teksten.
V2 = {
"Red Flames · KRC Genk Ladies · OH Leuven · Sporting Hasselt": ("Red Flames · KRC Genk Ladies · OH Leuven · Sporting Hasselt","Red Flames · KRC Genk Ladies · OH Leuven · Sporting Hasselt"),
"Credo Rehab &amp; Performance &middot; BTW BE 0756.834.184": ("Credo Rehab &amp; Performance &middot; VAT BE 0756.834.184","Credo Rehab &amp; Performance &middot; TVA BE 0756.834.184"),
"Bankdruk in het rek en optrekken aan de rekstok.": ("Bench press in the rack and pull-ups on the bar.","D&eacute;velopp&eacute; couch&eacute; dans le rack et tractions &agrave; la barre."),
"Pati&euml;nte loopt weer vrij op de indoorpiste.": ("A patient runs freely again on the indoor track.","Une patiente court de nouveau librement sur la piste int&eacute;rieure."),
"Kinesiste in de zaal tijdens het intakegesprek.": ("A physiotherapist in the gym during the intake conversation.","Une kin&eacute;sith&eacute;rapeute dans la salle pendant l&rsquo;entretien d&rsquo;anamn&egrave;se."),
"Op tien minuten van Hasselt, met ruime parking.": ("Ten minutes from Hasselt, with ample parking.","&Agrave; dix minutes de Hasselt, avec un grand parking."),
"Portret van Rimke Eurlings, kinesist bij Credo.": ("Portrait of Rimke Eurlings, physiotherapist at Credo.","Portrait de Rimke Eurlings, kin&eacute;sith&eacute;rapeute chez Credo."),
"Atlete met dumbbells, klaar voor de screening.": ("An athlete with dumbbells, ready for the screening.","Une athl&egrave;te avec des halt&egrave;res, pr&ecirc;te pour le screening."),
"Atlete trekt zich op aan de riemen in het rek.": ("An athlete pulls herself up on the straps in the rack.","Une athl&egrave;te se hisse aux sangles dans le rack."),
"Kinesitherapie &amp; revalidatie in Diepenbeek": ("Physiotherapy &amp; rehabilitation in Diepenbeek","Kin&eacute;sith&eacute;rapie &amp; revalidation &agrave; Diepenbeek"),
"Kinesitherapeut Sporting Hasselt (2025–heden)": ("Physiotherapist, Sporting Hasselt (2025–present)","Kin&eacute;sith&eacute;rapeute, Sporting Hasselt (2025–aujourd&rsquo;hui)"),
"Logo van de Koninklijke Belgische Voetbalbond": ("Logo of the Royal Belgian Football Association","Logo de l&rsquo;Union belge de football"),
"Portret van Bas Van Bael, kinesist bij Credo.": ("Portrait of Bas Van Bael, physiotherapist at Credo.","Portrait de Bas Van Bael, kin&eacute;sith&eacute;rapeute chez Credo."),
"Twee atleten voor de mosmuur na de training.": ("Two athletes in front of the moss wall after training.","Deux athl&egrave;tes devant le mur v&eacute;g&eacute;tal apr&egrave;s l&rsquo;entra&icirc;nement."),
"Naar Credo Personal Training en Performance": ("To Credo Personal Training and Performance","Vers Credo Personal Training et Performance"),
"Strength coach Sporting Hasselt (2025–2026)": ("Strength coach, Sporting Hasselt (2025–2026)","Strength coach, Sporting Hasselt (2025–2026)"),
"Toon credentials van Milan Vandecaetsbeek": ("Show credentials of Milan Vandecaetsbeek","Afficher les qualifications de Milan Vandecaetsbeek"),
"Naar Credo Revalidatie en Kinesitherapie": ("To Credo Rehabilitation and Physiotherapy","Vers Credo Revalidation et Kin&eacute;sith&eacute;rapie"),
"Naar personal training &amp; performance": ("To personal training &amp; performance","Vers personal training &amp; performance"),
"Atleet onder de stang in het krachtrek.": ("An athlete under the bar in the power rack.","Un athl&egrave;te sous la barre dans le power rack."),
"Kapelstraat 89 &middot; 3590 Diepenbeek": ("Kapelstraat 89 &middot; 3590 Diepenbeek","Kapelstraat 89 &middot; 3590 Diepenbeek"),
"Toon credentials van Philippe Valvekens": ("Show credentials of Philippe Valvekens","Afficher les qualifications de Philippe Valvekens"),
"Toon credentials van Tuur Vanderstukken": ("Show credentials of Tuur Vanderstukken","Afficher les qualifications de Tuur Vanderstukken"),
"Atlete in de zaal, vlak voor de start.": ("An athlete in the gym, just before the start.","Une athl&egrave;te dans la salle, juste avant le d&eacute;part."),
"Credo Rehab en Performance, naar boven": ("Credo Rehab and Performance, back to top","Credo Rehab et Performance, retour en haut"),
"Moet ik sporter zijn om hier te komen?": ("Do I have to be an athlete to come here?","Faut-il &ecirc;tre sportif pour venir ici&nbsp;?"),
"Oleg Cheprassov &middot; Google-review": ("Oleg Cheprassov &middot; Google review","Oleg Cheprassov &middot; avis Google"),
"Physical coach Genk Ladies (2024–2026)": ("Physical coach, Genk Ladies (2024–2026)","Physical coach, Genk Ladies (2024–2026)"),
"Toon credentials van Dries Verschueren": ("Show credentials of Dries Verschueren","Afficher les qualifications de Dries Verschueren"),
"Atlete loopt over de steps op de mat.": ("An athlete runs over the steps on the turf.","Une athl&egrave;te court sur les steps du tapis."),
"Naar revalidatie &amp; kinesitherapie": ("To rehabilitation &amp; physiotherapy","Vers revalidation &amp; kin&eacute;sith&eacute;rapie"),
"Physical coach Lommel SK (2026–heden)": ("Physical coach, Lommel SK (2026–present)","Physical coach, Lommel SK (2026–aujourd&rsquo;hui)"),
"Kaan Tanriver &middot; Google-review": ("Kaan Tanriver &middot; Google review","Kaan Tanriver &middot; avis Google"),
"Latijns voor &lsquo;ik geloof&rsquo;": ("Latin for &lsquo;I believe&rsquo;","Latin pour &lsquo;je crois&rsquo;"),
"Physical coach OH Leuven (2025–2026)": ("Physical coach, OH Leuven (2025–2026)","Physical coach, OH Leuven (2025–2026)"),
"Voor welke leeftijd is dit geschikt?": ("What ages is this suitable for?","&Agrave; quel &acirc;ge cela convient-il&nbsp;?"),
"Coach Sporting Hasselt (2021–heden)": ("Coach, Sporting Hasselt (2021–present)","Coach, Sporting Hasselt (2021–aujourd&rsquo;hui)"),
"Gitte Reners &middot; Google-review": ("Gitte Reners &middot; Google review","Gitte Reners &middot; avis Google"),
"Personal training &amp; performance": ("Personal training &amp; performance","Personal training &amp; performance"),
"Toon credentials van Rimke Eurlings": ("Show credentials of Rimke Eurlings","Afficher les qualifications de Rimke Eurlings"),
"van jeugdspelers tot internationals": ("from youth players to internationals","des jeunes joueurs aux internationaux"),
"Toon credentials van Thomas Casier": ("Show credentials of Thomas Casier","Afficher les qualifications de Thomas Casier"),
"Toon credentials van Bas Van Bael": ("Show credentials of Bas Van Bael","Afficher les qualifications de Bas Van Bael"),
"Kan dit naast mijn clubtraining?": ("Can this run alongside my club training?","Est-ce compatible avec mes entra&icirc;nements en club&nbsp;?"),
"Revalidatie &amp; kinesitherapie": ("Rehabilitation &amp; physiotherapy","Revalidation &amp; kin&eacute;sith&eacute;rapie"),
"Blood flow restriction training": ("Blood flow restriction training","Blood flow restriction training"),
"Kinesitherapeut Torpedo Hasselt": ("Physiotherapist, Torpedo Hasselt","Kin&eacute;sith&eacute;rapeute, Torpedo Hasselt"),
"Staat je vraag er niet bij? Bel": ("Is your question not here? Call","Votre question n&rsquo;y figure pas&nbsp;? Appelez"),
"jongste tot oudste pati&euml;nt": ("youngest to oldest patient","du patient le plus jeune au plus &acirc;g&eacute;"),
"met &eacute;&eacute;n afspraak.": ("with one appointment.","par un rendez-vous."),
"Nog in revalidatie? Start hier": ("Still in rehabilitation? Start here","Encore en revalidation&nbsp;? Commencez ici"),
"Beelden uit de zaal van Credo": ("Images from the Credo gym","Images de la salle de Credo"),
"Heb ik een voorschrift nodig?": ("Do I need a referral?","Ai-je besoin d&rsquo;une prescription&nbsp;?"),
"Ma tot vr 08:00 &ndash; 21:00": ("Mon to Fri 08:00 &ndash; 21:00","Lun &agrave; ven 08:00 &ndash; 21:00"),
"Val&eacute;rie Vandecaetsbeek": ("Val&eacute;rie Vandecaetsbeek","Val&eacute;rie Vandecaetsbeek"),
"Logo van 6D Sports Nutrition": ("Logo of 6D Sports Nutrition","Logo de 6D Sports Nutrition"),
"Screening &amp; goal setting": ("Screening &amp; goal setting","Screening &amp; goal setting"),
"sporters &amp; niet-sporters": ("athletes &amp; non-athletes","sportifs &amp; non-sportifs"),
"info@credokinesitherapie.be": ("info@credokinesitherapie.be","info@credokinesitherapie.be"),
"Hoelang duurt een traject?": ("How long does a programme take?","Combien de temps dure un parcours&nbsp;?"),
"Kinesist &amp; zaakvoerder": ("Physiotherapist &amp; partner","Kin&eacute;sith&eacute;rapeute &amp; g&eacute;rant"),
"Krijg ik het terugbetaald?": ("Will it be reimbursed?","Est-ce rembours&eacute;&nbsp;?"),
"Krijg ik mijn cijfers mee?": ("Do I get my numbers?","Est-ce que je re&ccedil;ois mes chiffres&nbsp;?"),
"Praktijkassistent UHasselt": ("Teaching assistant, UHasselt","Assistant de pratique, UHasselt"),
"Specialisatie sportletsels": ("Specialisation in sports injuries","Sp&eacute;cialisation en l&eacute;sions sportives"),
"Specialisatie sportvoeding": ("Specialisation in sports nutrition","Sp&eacute;cialisation en nutrition sportive"),
"[&#712;kree&#720;do&#720;]": ("[&#712;kree&#720;do&#720;]","[&#712;kree&#720;do&#720;]"),
"Logo van Sporting Hasselt": ("Logo of Sporting Hasselt","Logo de Sporting Hasselt"),
"Logo van VALD Performance": ("Logo of VALD Performance","Logo de VALD Performance"),
"Physical coach Red Flames": ("Physical coach, Red Flames","Physical coach, Red Flames"),
"Welke sport en welk doel?": ("Which sport and which goal?","Quel sport et quel objectif&nbsp;?"),
"5&#8202;&ndash;&#8202;91": ("5&#8202;&ndash;&#8202;91","5&#8202;&ndash;&#8202;91"),
"Logo van Forward Hasselt": ("Logo of Forward Hasselt","Logo de Forward Hasselt"),
"Logo van KRC Genk Ladies": ("Logo of KRC Genk Ladies","Logo de KRC Genk Ladies"),
"Logo van Torpedo Hasselt": ("Logo of Torpedo Hasselt","Logo de Torpedo Hasselt"),
"RBFA &middot; Red Flames": ("RBFA &middot; Red Flames","URBSFA &middot; Red Flames"),
"Toon alle samenwerkingen": ("Show all partnerships","Afficher tous les partenariats"),
"Vijf van de vijf sterren": ("Five out of five stars","Cinq &eacute;toiles sur cinq"),
"&Eacute;&eacute;n doel.": ("One goal.","Un objectif."),
"Maandag &ndash; vrijdag": ("Monday &ndash; Friday","Lundi &ndash; vendredi"),
"Master manuele therapie": ("Master in manual therapy","Master en th&eacute;rapie manuelle"),
"Rehab &amp; Performance": ("Rehab &amp; Performance","Rehab &amp; Performance"),
"Vooruitgang die blijft.": ("Progress that lasts.","Des progr&egrave;s qui durent."),
"Wat kost een screening?": ("What does a screening cost?","Combien co&ucirc;te un screening&nbsp;?"),
"Wie je hierin begeleidt": ("Who guides you in this","Qui vous accompagne"),
"Intake &amp; screening": ("Intake &amp; screening","Anamn&egrave;se &amp; screening"),
"Ruime parking aanwezig": ("Ample parking available","Grand parking disponible"),
"Wat is er aan de hand?": ("What is going on?","Que se passe-t-il&nbsp;?"),
"Run&amp;Roast Hasselt": ("Run&amp;Roast Hasselt","Run&amp;Roast Hasselt"),
"Zaterdag &amp; zondag": ("Saturday &amp; Sunday","Samedi &amp; dimanche"),
"staan langs het veld.": ("are on the touchline.","sont au bord du terrain."),
"&amp; kinesitherapie": ("&amp; Physiotherapy","&amp; Kin&eacute;sith&eacute;rapie"),
"Bel +32 480 62 85 45": ("Call +32 480 62 85 45","Appelez le +32 480 62 85 45"),
"Milan Vandecaetsbeek": ("Milan Vandecaetsbeek","Milan Vandecaetsbeek"),
"Wat kost een sessie?": ("What does a session cost?","Combien co&ucirc;te une s&eacute;ance&nbsp;?"),
"Zo verloopt een blok": ("How a block runs","Comment se d&eacute;roule un bloc"),
"alleen uit te komen.": ("get through this alone.","vous en sortir seul."),
"bij ons terechtkunt.": ("come to us for.","vous pouvez venir."),
"08:00 &ndash; 21:00": ("08:00 &ndash; 21:00","08:00 &ndash; 21:00"),
"6D Sports Nutrition": ("6D Sports Nutrition","6D Sports Nutrition"),
"Functioneel trainen": ("Functional training","Entra&icirc;nement fonctionnel"),
"Herstel dat blijft.": ("Recovery that lasts.","Une r&eacute;cup&eacute;ration qui dure."),
"Samenwerkingen / 05": ("Partnerships / 05","Partenariats / 05"),
"Voor- en achternaam": ("First and last name","Pr&eacute;nom et nom"),
"Weer op eigen benen": ("Back on your own feet","De nouveau sur pied"),
"Bekijk het traject": ("See the programme","Voir le parcours"),
"Boek direct online": ("Book online now","R&eacute;servez en ligne"),
"Credo op Instagram": ("Credo on Instagram","Credo sur Instagram"),
"Hoe vaak per week?": ("How often per week?","&Agrave; quelle fr&eacute;quence par semaine&nbsp;?"),
"Kies een onderdeel": ("Choose a section","Choisissez une rubrique"),
"Kom sterker terug.": ("Come back stronger.","Revenez plus fort."),
"Logo van Lommel SK": ("Logo of Lommel SK","Logo de Lommel SK"),
"Logo van OH Leuven": ("Logo of OH Leuven","Logo de OH Leuven"),
"Philippe Valvekens": ("Philippe Valvekens","Philippe Valvekens"),
"Plan een onderzoek": ("Book an examination","Planifier un examen"),
"Toon de hele ploeg": ("Show the whole team","Afficher toute l&rsquo;&eacute;quipe"),
"Tuur Vanderstukken": ("Tuur Vanderstukken","Tuur Vanderstukken"),
"Volgende teamleden": ("Next team members","Membres suivants"),
"Zeven therapeuten.": ("Seven therapists.","Sept th&eacute;rapeutes."),
"voor ieder een fit": ("a match for everyone","un profil pour chacun"),
"&amp; Performance": ("&amp; Performance","&amp; Performance"),
"&amp; performance": ("&amp; performance","&amp; performance"),
"Bekijk het aanbod": ("See what we offer","Voir notre offre"),
"Boek een afspraak": ("Book an appointment","Prendre rendez-vous"),
"Credo op Facebook": ("Credo on Facebook","Credo sur Facebook"),
"Dries Verschueren": ("Dries Verschueren","Dries Verschueren"),
"Grenzen verleggen": ("Pushing your limits","Repousser ses limites"),
"Jeugdontwikkeling": ("Youth development","D&eacute;veloppement des jeunes"),
"Lees ze op Google": ("Read them on Google","Lisez-les sur Google"),
"Logo van Voetwerk": ("Logo of Voetwerk","Logo de Voetwerk"),
"Maak een afspraak": ("Book an appointment","Prendre rendez-vous"),
"Mobiele navigatie": ("Mobile navigation","Navigation mobile"),
"Personal Training": ("Personal Training","Personal Training"),
"Revalidatie &amp;": ("Rehabilitation &amp;","Revalidation &amp;"),
"Verstuur aanvraag": ("Send request","Envoyer la demande"),
"Wat breng ik mee?": ("What do I bring?","Qu&rsquo;est-ce que j&rsquo;apporte&nbsp;?"),
"Je hoeft er niet": ("You do not have to","Vous n&rsquo;avez pas &agrave;"),
"Logo van Vitruve": ("Logo of Vitruve","Logo de Vitruve"),
"Manuele therapie": ("Manual therapy","Th&eacute;rapie manuelle"),
"Michiel Partoens": ("Michiel Partoens","Michiel Partoens"),
"Naar hoofdinhoud": ("Skip to main content","Aller au contenu principal"),
"Naar performance": ("To performance","Vers performance"),
"Naar revalidatie": ("To rehabilitation","Vers revalidation"),
"Sporting Hasselt": ("Sporting Hasselt","Sporting Hasselt"),
"Vorige teamleden": ("Previous team members","Membres pr&eacute;c&eacute;dents"),
"Wat we doen / 02": ("What we do / 02","Ce que nous faisons / 02"),
"Weekend gesloten": ("Closed at weekends","Ferm&eacute; le week-end"),
"Zij begonnen ook": ("They too began","Eux aussi ont commenc&eacute;"),
"3590 Diepenbeek": ("3590 Diepenbeek","3590 Diepenbeek"),
"Ervaringen / 06": ("Experiences / 06","T&eacute;moignages / 06"),
"Forward Hasselt": ("Forward Hasselt","Forward Hasselt"),
"In cijfers / 04": ("In numbers / 04","En chiffres / 04"),
"KRC Genk Ladies": ("KRC Genk Ladies","KRC Genk Ladies"),
"Kapelstraat 89.": ("Kapelstraat 89.","Kapelstraat 89."),
"Meettechnologie": ("Measuring technology","Technologie de mesure"),
"Nationale ploeg": ("National team","&Eacute;quipe nationale"),
"Torpedo Hasselt": ("Torpedo Hasselt","Torpedo Hasselt"),
"Zo bouwen we op": ("How we build you up","Comment nous construisons"),
"is een methode.": ("is a method.","est une m&eacute;thode."),
"Eén standaard.": ("One standard.","Un seul standard."),
"Hoofdnavigatie": ("Main navigation","Navigation principale"),
"Kapelstraat 89": ("Kapelstraat 89","Kapelstraat 89"),
"Kinesitherapie": ("Physiotherapy","Kin&eacute;sith&eacute;rapie"),
"Meer van Credo": ("More from Credo","Plus de Credo"),
"Pati&euml;nten": ("Patients","Patients"),
"Praktisch / 09": ("Practical / 09","Pratique / 09"),
"Rimke Eurlings": ("Rimke Eurlings","Rimke Eurlings"),
"Specialisaties": ("Specialisations","Sp&eacute;cialisations"),
"je echt staat?": ("you really stand?","vous en &ecirc;tes vraiment&nbsp;?"),
"&amp; testing": ("&amp; testing","&amp; testing"),
"Afspraak / 10": ("Appointment / 10","Rendez-vous / 10"),
"Boek afspraak": ("Book now","R&eacute;server"),
"De vloer / 08": ("The floor / 08","La salle / 08"),
"Drie cijfers.": ("Three numbers.","Trois chiffres."),
"Fitter worden": ("Getting fitter","Se remettre en forme"),
"Kies een taal": ("Choose a language","Choisir une langue"),
"Oefentherapie": ("Exercise therapy","Th&eacute;rapie par l&rsquo;exercice"),
"Plan je route": ("Plan your route","Calculer l&rsquo;itin&eacute;raire"),
"Privacybeleid": ("Privacy policy","Politique de confidentialit&eacute;"),
"Stel je vraag": ("Ask your question","Posez votre question"),
"Thomas Casier": ("Thomas Casier","Thomas Casier"),
"Volgende foto": ("Next photo","Photo suivante"),
"Voor je belt.": ("Before you call.","Avant d&rsquo;appeler."),
"Wat patiënten": ("What patients","Ce que les patients"),
"Ze komen hier": ("They have been coming","Ils viennent ici"),
"de profsport.": ("professional sport.","du sport professionnel."),
"ervan zeggen.": ("say about it.","en disent."),
"Bas Van Bael": ("Bas Van Bael","Bas Van Bael"),
"Behandelplan": ("Treatment plan","Plan de traitement"),
"Dry needling": ("Dry needling","Dry needling"),
"Ervaring uit": ("Experience from","L&rsquo;exp&eacute;rience du"),
"Luna Vanzeir": ("Luna Vanzeir","Luna Vanzeir"),
"Openingsuren": ("Opening hours","Heures d&rsquo;ouverture"),
"Sportvoeding": ("Sports nutrition","Nutrition sportive"),
"Traject / 03": ("Programme / 03","Parcours / 03"),
"Zo werkt het": ("How it works","Comment &ccedil;a marche"),
"oude niveau.": ("old level.","ancien niveau."),
"Aanbod / 02": ("What we offer / 02","Notre offre / 02"),
"Behandeling": ("Treatment","Traitement"),
"Credentials": ("Credentials","Qualifications"),
"Menu openen": ("Open menu","Ouvrir le menu"),
"Onze mensen": ("Our people","Nos gens"),
"Performance": ("Performance","Performance"),
"Revalidatie": ("Rehab","Revalidation"),
"Therapeuten": ("Therapists","Th&eacute;rapeutes"),
"Toon minder": ("Show less","Afficher moins"),
"Vorige foto": ("Previous photo","Photo pr&eacute;c&eacute;dente"),
"Waarvoor je": ("What you can","Ce pour quoi"),
"Wat we doen": ("Services","Soins"),
"Credo / 01": ("Credo / 01","Credo / 01"),
"Jouw beurt": ("Your turn","&Agrave; votre tour"),
"Naar&nbsp;": ("To&nbsp;","Vers&nbsp;"),
"Profbokser": ("Professional boxer","Boxeur professionnel"),
"Red Flames": ("Red Flames","Red Flames"),
"Voorbij je": ("Beyond your","Au-del&agrave; de votre"),
"Weten waar": ("Want to know where","Savoir o&ugrave;"),
"Wil je een": ("Would you like an","Vous voulez un"),
"Kom langs": ("Visit us","Venez nous voir"),
"Lifestyle": ("Lifestyle","Mode de vie"),
"Lommel SK": ("Lommel SK","Lommel SK"),
"Materiaal": ("Equipment","Mat&eacute;riel"),
"Motivatie": ("Motivation","Motivation"),
"OH Leuven": ("OH Leuven","OH Leuven"),
"Praktisch": ("Practical","Pratique"),
"Profclubs": ("Pro clubs","Clubs pros"),
"Programma": ("Programme","Programme"),
"Screening": ("Screening","Screening"),
"Team / 07": ("Team / 07","&Eacute;quipe / 07"),
"Waarde 01": ("Value 01","Valeur 01"),
"Waarde 02": ("Value 02","Valeur 02"),
"Waarde 03": ("Value 03","Valeur 03"),
"afspraak?": ("appointment?","rendez-vous&nbsp;?"),
"al jaren.": ("here for years.","depuis des ann&eacute;es."),
"optioneel": ("optional","facultatif"),
"&middot;": ("&middot;","&middot;"),
"Afspraak": ("Appointment","Rendez-vous"),
"Empathie": ("Empathy","Empathie"),
"Gesloten": ("Closed","Ferm&eacute;"),
"Herstel.": ("Recover.","R&eacute;cup&eacute;rez."),
"Kinesist": ("Physiotherapist","Kin&eacute;sith&eacute;rapeute"),
"Ons doel": ("Our goal","Notre objectif"),
"Telefoon": ("Phone","T&eacute;l&eacute;phone"),
"Training": ("Training","Entra&icirc;nement"),
"Voetwerk": ("Voetwerk","Voetwerk"),
"Atleten": ("Athletes","Athl&egrave;tes"),
"Bel ons": ("Call us","Appelez-nous"),
"Contact": ("Contact","Contact"),
"Cookies": ("Cookies","Cookies"),
"Energie": ("Energy","&Eacute;nergie"),
"Hertest": ("Retest","Retest"),
"Inzicht": ("Insight","Perspicacit&eacute;"),
"Parking": ("Parking","Parking"),
"Stap 01": ("Step 01","&Eacute;tape 01"),
"Stap 02": ("Step 02","&Eacute;tape 02"),
"Stap 03": ("Step 03","&Eacute;tape 03"),
"Stap 04": ("Step 04","&Eacute;tape 04"),
"Stap 05": ("Step 05","&Eacute;tape 05"),
"Trainen": ("Train","S&rsquo;entra&icirc;ner"),
"Vitruve": ("Vitruve","Vitruve"),
"&copy;": ("&copy;","&copy;"),
"Aanbod": ("Services","Offre"),
"Aanpak": ("Approach","Approche"),
"Boeken": ("Book","R&eacute;server"),
"E-mail": ("Email","E-mail"),
"Opbouw": ("Build-up","Progression"),
"Passie": ("Passion","Passion"),
"Stride": ("Stride","Stride"),
"Studio": ("Studio","Studio"),
"Adres": ("Address","Adresse"),
"CREDO": ("CREDO","CREDO"),
"Credo": ("Credo","Credo"),
"Groei": ("Growth","Croissance"),
"Regio": ("Region","R&eacute;gion"),
"Club": ("Club","Club"),
"Doel": ("Goal","Objectif"),
"Jaar": ("Years","Ans"),
"Naam": ("Name","Nom"),
"Team": ("Team","&Eacute;quipe"),
"VALD": ("VALD","VALD"),
"info": ("info","info"),
"Bel": ("Call","Appeler"),
"EN": ("EN","EN"),
"FR": ("FR","FR"),
"NL": ("NL","NL"),
}
